import type { Snapshot } from "./types";
// Phase 1 only: explicit synthetic fixture. Production defaults to SQLite API.
export const demo: Snapshot = {
  today: "2026-10-01",
  items: [
    ["laptop", "MacBook Air M2", "Apple", "13.6 英寸 256GB", "数码", 8999],
    ["headphones", "Sony WH-1000XM6", "Sony", "WH-1000XM6", "数码", 2999],
    ["washer", "海尔滚筒洗衣机", "Haier", "EG100MATE8S", "家电", 3299],
    ["ac", "美的空调", "Midea", "KFR-35GW", "家电", 2899],
    ["robot", "小米扫地机器人", "Xiaomi", "S10", "家电", 1699],
    ["coffee", "德龙咖啡机", "DeLonghi", "EC685", "家电", 1599],
    ["toothbrush", "电动牙刷", "Philips", "HX6850", "数码", 399],
    ["suitcase", "行李箱", "RIMOWA", "Original Cabin", "家居", 1200],
    ["purifier", "空气净化器", "Xiaomi", "Air 4", "家电", 999],
    ["ink", "惠普打印机", "HP", "DeskJet 2720", "数码", 599],
  ].map((a, i) => ({
    id: String(a[0]),
    name: String(a[1]),
    brand: String(a[2]),
    model: String(a[3]),
    category: String(a[4]),
    purchasePrice: Number(a[5]),
    description: "合成演示档案",
    purchaseDate: "2026-01-10",
    purchaseChannel: "演示购买渠道",
    serialNumber: `WS-DEMO-${i + 1}`,
    warrantyMonths: 12,
    warrantyEndDate: "2027-01-10",
    returnDeadline: "2026-01-17",
    returnWindowDays: 7,
    status: i === 2 ? "维修中" : "正常使用",
    coverImage: `/assets/${a[0]}.jpg`,
    location: "客厅",
    isDemo: true,
    createdAt: "2026-10-01",
    updatedAt: "2026-10-01",
    warrantyDaysLeft: 101,
    nextMaintenance: i === 2 ? "2026-10-03" : null,
  })),
  reminders: [],
  repairs: [],
  consumables: [],
  stats: {
    itemCount: 10,
    warrantyCount: 10,
    maintenanceDue: 1,
    consumableLow: 0,
    warrantyCoverage: 100,
    annualMaintenance: 0,
    repairSpend: 0,
    consumableSpend: 0,
    monthlyConsumption: 0,
    categories: [
      { name: "家电", value: 5 },
      { name: "数码", value: 4 },
      { name: "家居", value: 1 },
    ],
    reminderTrend: [],
    maintenanceRanking: [],
    warrantyDistribution: [],
    consumableTrend: [],
    insights: ["Phase 1 合成演示数据，后续迁移 SQLite。"],
  },
};
